apply plugin: 'com.android.application'

import com.android.build.OutputFile

def keystoreProperties = new Properties()

def keystorePropertiesFile = rootProject.file("keystore.properties")
if (keystorePropertiesFile.exists()) {
  keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

// Override with ENV
if (System.getenv('STORE_PASSWORD')) {
  keystoreProperties['storePassword'] = System.getenv('STORE_PASSWORD')
}
if (System.getenv('STORE_PASSWORD')) {
  keystoreProperties['keyAlias'] = System.getenv('KEY_ALIAS')
}

// Map for the version code that gives each ABI a value.
ext.abiCodes = ['armeabi-v7a':0, 'arm64-v8a':1]

android {
  aaptOptions {
    noCompress 'assetbundle'
  }

  lintOptions {
    abortOnError false
    checkReleaseBuilds false
  }

  splits {
    abi {
      // Enables building multiple APKs per ABI.
      enable true

      // By default all ABIs are included, so use reset() and include to specify that we only
      // want APKs for x86 and x86_64.

      // Resets the list of ABIs that Gradle should create APKs for to none.
      reset()

      // Specifies a list of ABIs that Gradle should create APKs for.
      include "armeabi-v7a", "arm64-v8a"

      // Specifies that we do not want to also generate a universal APK that includes all ABIs.
      universalApk false
    }
  }

  signingConfigs {
    debug {
      keyAlias 'androiddebugkey'
      storeFile file('debug.keystore')
      storePassword 'android'
      keyPassword 'android'
    }

    release {
      keyAlias keystoreProperties['keyAlias']
      storeFile file('release.keystore')
      storePassword keystoreProperties['storePassword']
      keyPassword keystoreProperties['storePassword']
    }
  }

  compileOptions {
    sourceCompatibility 1.8
    targetCompatibility 1.8
  }
  
  compileSdkVersion 31
  buildToolsVersion "31.0.0"
  defaultConfig {
    applicationId "com.bagelcode.v3"
    minSdkVersion 19
    targetSdkVersion 31
    multiDexEnabled true
    versionCode project.hasProperty('versionCode') ? project.property('versionCode') as int : 1
    versionName project.hasProperty('versionName') ? project.property('versionName') : "1.0"
    if (System.getenv('BUILD_TAG')) {
      setProperty("archivesBaseName", System.getenv('BUILD_TAG'))
    }
  }
  sourceSets {
    main {
      assets.srcDirs += 'unity/src/main/assets'
      res.srcDirs += 'unity/src/main/res'
      jniLibs.srcDirs += 'unity/src/main/jniLibs'
    }
  }
  buildTypes {
    local {
      versionNameSuffix "-local"
      signingConfig signingConfigs.debug
      matchingFallbacks = ['debug', 'release']
    }
    team {
      versionNameSuffix "-team"
      applicationIdSuffix ".team"
      signingConfig signingConfigs.debug
      matchingFallbacks = ['debug', 'release']
    }
    teamcontents {
      versionNameSuffix "-teamcontents"
      applicationIdSuffix ".teamcontents"
      signingConfig signingConfigs.debug
      matchingFallbacks = ['debug', 'release']
    }
    qa {
      versionNameSuffix "-qa"
      signingConfig signingConfigs.release
      matchingFallbacks = ['debug', 'release']
    }
    st {
      versionNameSuffix "-st"
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'unity/proguard-unity.txt'
      signingConfig signingConfigs.release
      matchingFallbacks = ['release', 'debug']
    }
    prod {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'unity/proguard-unity.txt'
      signingConfig signingConfigs.release
      matchingFallbacks = ['release', 'debug']
    }
  }

  packagingOptions {
    doNotStrip '*/armeabi-v7a/*.so'
    doNotStrip '*/arm64-v8a/*.so'
  }

  flavorDimensions "default"

  productFlavors {
    slots1 {
      applicationId "com.bagelcode.slots1"

      resValue 'string', 'product_name', 'Club Vegas'
      resValue 'string', 'adjust_app_token', 'qrclojmqdngg'
      resValue 'string', 'adjust_env', 'production'
      resValue 'string', 'adjust_app_secret', '3'
      resValue 'string', 'adjust_info1', '2007335413'
      resValue 'string', 'adjust_info2', '529047663'
      resValue 'string', 'adjust_info3', '509835225'
      resValue 'string', 'adjust_info4', '1124383547'
      resValue 'string', 'app_download_url', 'market://details?id=' + applicationId
    }

    slots3 {
      applicationId "com.bagelcode.slots3"

      resValue 'string', 'product_name', 'Cash Billionaire'
      resValue 'string', 'adjust_app_token', 'dmyp1500xqm8'
      resValue 'string', 'adjust_env', 'production'
      resValue 'string', 'adjust_app_secret', '3'
      resValue 'string', 'adjust_info1', '1246956143'
      resValue 'string', 'adjust_info2', '1755911371'
      resValue 'string', 'adjust_info3', '883156095'
      resValue 'string', 'adjust_info4', '2127909427'
      resValue 'string', 'app_download_url', 'market://details?id=' + applicationId
    }

    slots4 {
      applicationId "com.cashworldslots.slots1"

      resValue 'string', 'product_name', 'Cash World'
      resValue 'string', 'adjust_app_token', 'gnv9xd1o7w8w'
      resValue 'string', 'adjust_env', 'production'
      resValue 'string', 'adjust_app_secret', '1'
      resValue 'string', 'adjust_info1', '922363205'
      resValue 'string', 'adjust_info2', '2060639489'
      resValue 'string', 'adjust_info3', '1683252458'
      resValue 'string', 'adjust_info4', '323448519'
      resValue 'string', 'app_download_url', 'market://details?id=' + applicationId
    }
  }

  android.applicationVariants.all { variant ->
    // Facebook, OneSignal
    def facebookAppId, onesignalAppId
    
    def variantName = variant.getName()
    switch(variantName) {            
      case 'slots1Prod':
        facebookAppId = "1881581215396162"
        onesignalAppId = "f6d06531-c29b-4e9d-83d4-b910c4f6c053"
        break

      case 'slots1Qa':
        facebookAppId = "131332947544414"
        onesignalAppId = "610ba85e-5d31-4afc-b95f-c060ef3a2772"
        break

      case 'slots1Team':
      case 'slots1Teamcontents':
        facebookAppId = "1898338550387095"
        onesignalAppId = "d3818ad5-d87f-4ca0-a067-0a53af0047e7"
        break

      case 'slots3Prod':
        facebookAppId = "462253681467734"
        onesignalAppId = "bd9ed2c5-45db-48bb-bfff-e2088b67817b"
        break

      case 'slots3Qa':
        facebookAppId = "899695047455167"
        onesignalAppId = "9661e45d-6aa1-42fe-ab46-6398eef45b15"
        break

      case 'slots3Team':
        facebookAppId = "801929007067813"
        onesignalAppId = "9e1682c3-aa0f-429d-8e8e-178de7bbf050"
        break

      case 'slots4Prod':
        facebookAppId = "462253681467734"
        onesignalAppId = "8516ed87-2af4-4cb5-9f87-1d5080fb6f79"
        break

      case 'slots4Qa':
        facebookAppId = "899695047455167"
        onesignalAppId = "80c8ae2a-bc54-4cbf-b5dc-932c70edde9c"
        break

      case 'slots4Team':
        facebookAppId = "801929007067813"
        onesignalAppId = "8ceab4b9-0c89-46a8-b1a4-697735a3e9d4"
        break

      default:
        facebookAppId = "1898338550387095"
        onesignalAppId = "d3818ad5-d87f-4ca0-a067-0a53af0047e7"
        
        println(variantName)
        break
    }

    def mergedFlavor = variant.getMergedFlavor()
    mergedFlavor.manifestPlaceholders = [
      facebookAppId: facebookAppId
    ]

    variant.resValue 'string', 'facebook_app_id', facebookAppId
    variant.resValue 'string', 'fb_login_protocol_scheme', ("fb" + facebookAppId)
    variant.resValue 'string', 'onesignal_app_id', onesignalAppId

    def appName = variant.mergedFlavor.resValues.get('product_name').getValue()

    if (variant.buildType.name != "prod") {
      appName = "${variant.buildType.name} ${appName}"
      variant.resValue 'string', 'adjust_env', 'sandbox'
    }
    // set new resVale
    variant.resValue 'string', 'product_name', appName

    // Assigns a different version code for each output APK
    // other than the universal APK.
    variant.outputs.each { output ->

      // Stores the value of ext.abiCodes that is associated with the ABI for this variant.
      def baseAbiVersionCode =
        // Determines the ABI for this variant and returns the mapped value.
        project.ext.abiCodes.get(output.getFilter(OutputFile.ABI))

      // Because abiCodes.get() returns null for ABIs that are not mapped by ext.abiCodes,
      // the following code does not override the version code for universal APKs.
      // However, because we want universal APKs to have the lowest version code,
      // this outcome is desirable.
      if (baseAbiVersionCode != null) {

        // Assigns the new version code to versionCodeOverride, which changes the version code
        // for only the output APK, not for the variant itself. Skipping this step simply
        // causes Gradle to use the value of variant.versionCode for the APK.
        output.versionCodeOverride =
          baseAbiVersionCode + variant.versionCode
      }
    }
  }
}
repositories {
  mavenCentral()
  // maven { url "https://dl.bintray.com/ironsource-mobile/android-sdk" }
  // maven { url "https://dl.bintray.com/ironsource-mobile/android-adapters" }
  // maven { url 'https://maven.fabric.io/public' }
  maven { url 'https://jitpack.io' }

  maven { url 'https://android-sdk.is.com/'}
  maven { url "https://sdk.tapjoy.com/"}

}
dependencies {
  def billing_version = "4.0.0"
  implementation "com.android.billingclient:billing:$billing_version"

  implementation fileTree(dir: 'unity/libs', include: ['*.jar'])
  implementation 'com.android.support:appcompat-v7:27.1.1'

  implementation 'com.facebook.android:facebook-android-sdk:12.2.0'
  implementation 'com.theartofdev.edmodo:android-image-cropper:2.7.0'
  implementation 'com.google.android.gms:play-services-analytics:17.0.0'

  // For multidex
  implementation 'com.android.support:multidex:1.0.3'
  /////////////////
  // IronSource
  implementation 'com.ironsource.sdk:mediationsdk:7.2.6'
  implementation fileTree(dir: 'libs', include: ['*.jar']) 
  implementation 'com.google.android.gms:play-services-appset:16.0.0'
  implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
  implementation 'com.google.android.gms:play-services-basement:18.1.0'
  /////
  // Add AdMob and Ad Manager Network
  implementation 'com.google.android.gms:play-services-ads:21.3.0'
  implementation 'com.ironsource.adapters:admobadapter:4.3.32'
  // Add Applovin Network
  implementation 'com.ironsource.adapters:applovinadapter:4.3.35'
  implementation 'com.applovin:applovin-sdk:11.5.5'
  // Add Facebook Network
  implementation 'com.ironsource.adapters:facebookadapter:4.3.38'
  implementation 'com.facebook.android:audience-network-sdk:6.12.0'
  // Add Tapjoy Network
  implementation 'com.ironsource.adapters:tapjoyadapter:4.1.22'
  implementation 'com.tapjoy:tapjoy-android-sdk:12.11.0'
  // Add Vungle Network
  implementation 'com.ironsource.adapters:vungleadapter:4.3.18'
  implementation 'com.vungle:publisher-sdk-android:6.12.0'
  // Add Ad Quality
  // implementation 'com.ironsource:adqualitysdk:7.4.0'
  /////////////////
  implementation 'com.google.dagger:dagger:2.7'
  implementation 'javax.inject:javax.inject:1'
  implementation 'de.greenrobot:eventbus:2.2.1'
  implementation 'io.reactivex:rxjava:1.2.0'
  implementation 'io.reactivex:rxandroid:1.2.1'
  implementation 'com.squareup.okhttp3:okhttp:3.6.0'
  implementation 'com.squareup.okio:okio:1.11.0'
  implementation 'com.squareup.retrofit2:retrofit:2.2.0'
  implementation 'com.squareup.retrofit2:converter-gson:2.2.0'
  implementation 'com.squareup.retrofit2:adapter-rxjava:2.2.0'
  implementation 'com.google.code.gson:gson:2.7'
  ////
  // Adjust
  implementation 'com.adjust.sdk:adjust-android:4.33.0'
  implementation 'com.android.installreferrer:installreferrer:2.2'
  ////
  
  // for Onesignal
  implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'

  // SurveyMonkey
  implementation 'com.surveymonkey:surveymonkey-android-sdk:1.0.6'

  implementation 'com.google.android.gms:play-services-auth:17.0.0'

  ////// Firebase
  implementation platform('com.google.firebase:firebase-bom:29.3.1')
  implementation 'com.google.firebase:firebase-analytics'
  implementation 'com.google.firebase:firebase-crashlytics'
  //////

  implementation(name:'adjust_sig_v2_lib', ext:'aar')
}

task reverseForward(type: Exec) {
  def adb  = android.getAdbExe().toString()
  def forwardLogicCommand = [adb, 'reverse', 'tcp:20000', 'tcp:20000']
  commandLine forwardLogicCommand
  def forwardAdminCommand = [adb, 'reverse', 'tcp:21000', 'tcp:21000']
  commandLine forwardAdminCommand
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
