//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/common.proto
namespace rpc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcPacket")]
  public partial class RpcPacket : global::ProtoBuf.IExtensible
  {
    public RpcPacket() {}
    
    private uint _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private uint _SubMsgId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SubMsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SubMsgId
    {
      get { return _SubMsgId; }
      set { _SubMsgId = value; }
    }
    private rpc.SERVICE _ServiceType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ServiceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public rpc.SERVICE ServiceType
    {
      get { return _ServiceType; }
      set { _ServiceType = value; }
    }
    private uint _SrcClusterId = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SrcClusterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SrcClusterId
    {
      get { return _SrcClusterId; }
      set { _SrcClusterId = value; }
    }
    private uint _DstClusterId = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"DstClusterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint DstClusterId
    {
      get { return _DstClusterId; }
      set { _DstClusterId = value; }
    }
    private byte[] _RpcBody = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"RpcBody", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] RpcBody
    {
      get { return _RpcBody; }
      set { _RpcBody = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SERVICE")]
    public enum SERVICE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT", Value=1)]
      CLIENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APISERVER", Value=2)]
      APISERVER = 2
    }
  
}