//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/hall.proto
namespace hall
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartHeat")]
  public partial class HeartHeat : global::ProtoBuf.IExtensible
  {
    public HeartHeat() {}
    
    private ulong _SendTime = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong SendTime
    {
      get { return _SendTime; }
      set { _SendTime = value; }
    }
    private ulong _ReceiveTime = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ReceiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ReceiveTime
    {
      get { return _ReceiveTime; }
      set { _ReceiveTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomStatusInfo")]
  public partial class RoomStatusInfo : global::ProtoBuf.IExtensible
  {
    public RoomStatusInfo() {}
    
    private uint _game_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _room_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private string _room_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"room_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string room_name
    {
      get { return _room_name; }
      set { _room_name = value; }
    }
    private ulong _enter_min = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"enter_min", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong enter_min
    {
      get { return _enter_min; }
      set { _enter_min = value; }
    }
    private ulong _enter_max = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"enter_max", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong enter_max
    {
      get { return _enter_max; }
      set { _enter_max = value; }
    }
    private uint _status = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginHallReq")]
  public partial class LoginHallReq : global::ProtoBuf.IExtensible
  {
    public LoginHallReq() {}
    
    private string _playerId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginHallRsp")]
  public partial class LoginHallRsp : global::ProtoBuf.IExtensible
  {
    public LoginHallRsp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<hall.RoomStatusInfo> _rooms = new global::System.Collections.Generic.List<hall.RoomStatusInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<hall.RoomStatusInfo> rooms
    {
      get { return _rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameReq")]
  public partial class EnterGameReq : global::ProtoBuf.IExtensible
  {
    public EnterGameReq() {}
    
    private uint _game_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _room_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private uint _desk_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desk_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint desk_id
    {
      get { return _desk_id; }
      set { _desk_id = value; }
    }
    private uint _chair_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chair_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chair_id
    {
      get { return _chair_id; }
      set { _chair_id = value; }
    }
    private uint _proxy_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"proxy_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint proxy_id
    {
      get { return _proxy_id; }
      set { _proxy_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterGameRsp")]
  public partial class EnterGameRsp : global::ProtoBuf.IExtensible
  {
    public EnterGameRsp() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _chair_count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chair_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chair_count
    {
      get { return _chair_count; }
      set { _chair_count = value; }
    }
    private uint _my_chair_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"my_chair_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint my_chair_id
    {
      get { return _my_chair_id; }
      set { _my_chair_id = value; }
    }
    private uint _game_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }
    private uint _room_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private uint _game_bus_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"game_bus_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_bus_id
    {
      get { return _game_bus_id; }
      set { _game_bus_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitGameReq")]
  public partial class ExitGameReq : global::ProtoBuf.IExtensible
  {
    public ExitGameReq() {}
    
    private uint _reserved = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reserved", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reserved
    {
      get { return _reserved; }
      set { _reserved = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitGameRsp")]
  public partial class ExitGameRsp : global::ProtoBuf.IExtensible
  {
    public ExitGameRsp() {}
    
    private uint _exit_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"exit_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exit_type
    {
      get { return _exit_type; }
      set { _exit_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"HALL_CMD")]
    public enum HALL_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_LOGIN_Req", Value=2100)]
      HALL_CMD_LOGIN_Req = 2100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_LOGIN_Rsp", Value=2101)]
      HALL_CMD_LOGIN_Rsp = 2101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_HeartHeat_Req", Value=2102)]
      HALL_CMD_HeartHeat_Req = 2102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_HeartHeat_Rsp", Value=2103)]
      HALL_CMD_HeartHeat_Rsp = 2103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_FishGame_Req", Value=2104)]
      HALL_CMD_FishGame_Req = 2104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_FishGame_Rsp", Value=2105)]
      HALL_CMD_FishGame_Rsp = 2105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_EnterGame_Req", Value=2106)]
      HALL_CMD_EnterGame_Req = 2106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_EnterGame_Rsp", Value=2107)]
      HALL_CMD_EnterGame_Rsp = 2107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_ExitGame_Req", Value=2108)]
      HALL_CMD_ExitGame_Req = 2108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_CMD_ExitGame_Rsp", Value=2109)]
      HALL_CMD_ExitGame_Rsp = 2109
    }
  
}