// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace rpc
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RpcPacket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint MsgId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint SubMsgId
        {
            get => __pbn__SubMsgId.GetValueOrDefault();
            set => __pbn__SubMsgId = value;
        }
        public bool ShouldSerializeSubMsgId() => __pbn__SubMsgId != null;
        public void ResetSubMsgId() => __pbn__SubMsgId = null;
        private uint? __pbn__SubMsgId;

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public SERVICE ServiceType { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint SrcClusterId
        {
            get => __pbn__SrcClusterId.GetValueOrDefault();
            set => __pbn__SrcClusterId = value;
        }
        public bool ShouldSerializeSrcClusterId() => __pbn__SrcClusterId != null;
        public void ResetSrcClusterId() => __pbn__SrcClusterId = null;
        private uint? __pbn__SrcClusterId;

        [global::ProtoBuf.ProtoMember(5)]
        public uint DstClusterId
        {
            get => __pbn__DstClusterId.GetValueOrDefault();
            set => __pbn__DstClusterId = value;
        }
        public bool ShouldSerializeDstClusterId() => __pbn__DstClusterId != null;
        public void ResetDstClusterId() => __pbn__DstClusterId = null;
        private uint? __pbn__DstClusterId;

        [global::ProtoBuf.ProtoMember(6)]
        public byte[] RpcBody
        {
            get => __pbn__RpcBody;
            set => __pbn__RpcBody = value;
        }
        public bool ShouldSerializeRpcBody() => __pbn__RpcBody != null;
        public void ResetRpcBody() => __pbn__RpcBody = null;
        private byte[] __pbn__RpcBody;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SERVICE
    {
        NONE = 0,
        CLIENT = 1,
        APISERVER = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
