// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hall.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace hall
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HeartHeat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong SendTime
        {
            get => __pbn__SendTime.GetValueOrDefault();
            set => __pbn__SendTime = value;
        }
        public bool ShouldSerializeSendTime() => __pbn__SendTime != null;
        public void ResetSendTime() => __pbn__SendTime = null;
        private ulong? __pbn__SendTime;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ReceiveTime
        {
            get => __pbn__ReceiveTime.GetValueOrDefault();
            set => __pbn__ReceiveTime = value;
        }
        public bool ShouldSerializeReceiveTime() => __pbn__ReceiveTime != null;
        public void ResetReceiveTime() => __pbn__ReceiveTime = null;
        private ulong? __pbn__ReceiveTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomStatusInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private uint? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint room_id
        {
            get => __pbn__room_id.GetValueOrDefault();
            set => __pbn__room_id = value;
        }
        public bool ShouldSerializeroom_id() => __pbn__room_id != null;
        public void Resetroom_id() => __pbn__room_id = null;
        private uint? __pbn__room_id;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string room_name
        {
            get => __pbn__room_name ?? "";
            set => __pbn__room_name = value;
        }
        public bool ShouldSerializeroom_name() => __pbn__room_name != null;
        public void Resetroom_name() => __pbn__room_name = null;
        private string __pbn__room_name;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong enter_min
        {
            get => __pbn__enter_min.GetValueOrDefault();
            set => __pbn__enter_min = value;
        }
        public bool ShouldSerializeenter_min() => __pbn__enter_min != null;
        public void Resetenter_min() => __pbn__enter_min = null;
        private ulong? __pbn__enter_min;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong enter_max
        {
            get => __pbn__enter_max.GetValueOrDefault();
            set => __pbn__enter_max = value;
        }
        public bool ShouldSerializeenter_max() => __pbn__enter_max != null;
        public void Resetenter_max() => __pbn__enter_max = null;
        private ulong? __pbn__enter_max;

        [global::ProtoBuf.ProtoMember(6)]
        public uint status
        {
            get => __pbn__status.GetValueOrDefault();
            set => __pbn__status = value;
        }
        public bool ShouldSerializestatus() => __pbn__status != null;
        public void Resetstatus() => __pbn__status = null;
        private uint? __pbn__status;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginHallReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string playerId
        {
            get => __pbn__playerId ?? "";
            set => __pbn__playerId = value;
        }
        public bool ShouldSerializeplayerId() => __pbn__playerId != null;
        public void ResetplayerId() => __pbn__playerId = null;
        private string __pbn__playerId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginHallRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int result
        {
            get => __pbn__result.GetValueOrDefault();
            set => __pbn__result = value;
        }
        public bool ShouldSerializeresult() => __pbn__result != null;
        public void Resetresult() => __pbn__result = null;
        private int? __pbn__result;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<RoomStatusInfo> rooms { get; } = new global::System.Collections.Generic.List<RoomStatusInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterGameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private uint? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint room_id
        {
            get => __pbn__room_id.GetValueOrDefault();
            set => __pbn__room_id = value;
        }
        public bool ShouldSerializeroom_id() => __pbn__room_id != null;
        public void Resetroom_id() => __pbn__room_id = null;
        private uint? __pbn__room_id;

        [global::ProtoBuf.ProtoMember(3)]
        public uint desk_id
        {
            get => __pbn__desk_id.GetValueOrDefault();
            set => __pbn__desk_id = value;
        }
        public bool ShouldSerializedesk_id() => __pbn__desk_id != null;
        public void Resetdesk_id() => __pbn__desk_id = null;
        private uint? __pbn__desk_id;

        [global::ProtoBuf.ProtoMember(4)]
        public uint chair_id
        {
            get => __pbn__chair_id.GetValueOrDefault();
            set => __pbn__chair_id = value;
        }
        public bool ShouldSerializechair_id() => __pbn__chair_id != null;
        public void Resetchair_id() => __pbn__chair_id = null;
        private uint? __pbn__chair_id;

        [global::ProtoBuf.ProtoMember(5)]
        public uint proxy_id
        {
            get => __pbn__proxy_id.GetValueOrDefault();
            set => __pbn__proxy_id = value;
        }
        public bool ShouldSerializeproxy_id() => __pbn__proxy_id != null;
        public void Resetproxy_id() => __pbn__proxy_id = null;
        private uint? __pbn__proxy_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterGameRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int result
        {
            get => __pbn__result.GetValueOrDefault();
            set => __pbn__result = value;
        }
        public bool ShouldSerializeresult() => __pbn__result != null;
        public void Resetresult() => __pbn__result = null;
        private int? __pbn__result;

        [global::ProtoBuf.ProtoMember(2)]
        public uint chair_count
        {
            get => __pbn__chair_count.GetValueOrDefault();
            set => __pbn__chair_count = value;
        }
        public bool ShouldSerializechair_count() => __pbn__chair_count != null;
        public void Resetchair_count() => __pbn__chair_count = null;
        private uint? __pbn__chair_count;

        [global::ProtoBuf.ProtoMember(3)]
        public uint my_chair_id
        {
            get => __pbn__my_chair_id.GetValueOrDefault();
            set => __pbn__my_chair_id = value;
        }
        public bool ShouldSerializemy_chair_id() => __pbn__my_chair_id != null;
        public void Resetmy_chair_id() => __pbn__my_chair_id = null;
        private uint? __pbn__my_chair_id;

        [global::ProtoBuf.ProtoMember(4)]
        public uint game_id
        {
            get => __pbn__game_id.GetValueOrDefault();
            set => __pbn__game_id = value;
        }
        public bool ShouldSerializegame_id() => __pbn__game_id != null;
        public void Resetgame_id() => __pbn__game_id = null;
        private uint? __pbn__game_id;

        [global::ProtoBuf.ProtoMember(5)]
        public uint room_id
        {
            get => __pbn__room_id.GetValueOrDefault();
            set => __pbn__room_id = value;
        }
        public bool ShouldSerializeroom_id() => __pbn__room_id != null;
        public void Resetroom_id() => __pbn__room_id = null;
        private uint? __pbn__room_id;

        [global::ProtoBuf.ProtoMember(6)]
        public uint game_bus_id
        {
            get => __pbn__game_bus_id.GetValueOrDefault();
            set => __pbn__game_bus_id = value;
        }
        public bool ShouldSerializegame_bus_id() => __pbn__game_bus_id != null;
        public void Resetgame_bus_id() => __pbn__game_bus_id = null;
        private uint? __pbn__game_bus_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExitGameReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint reserved
        {
            get => __pbn__reserved.GetValueOrDefault();
            set => __pbn__reserved = value;
        }
        public bool ShouldSerializereserved() => __pbn__reserved != null;
        public void Resetreserved() => __pbn__reserved = null;
        private uint? __pbn__reserved;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExitGameRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint exit_type
        {
            get => __pbn__exit_type.GetValueOrDefault();
            set => __pbn__exit_type = value;
        }
        public bool ShouldSerializeexit_type() => __pbn__exit_type != null;
        public void Resetexit_type() => __pbn__exit_type = null;
        private uint? __pbn__exit_type;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum HALL_CMD
    {
        HALL_CMD_LOGIN_Req = 2100,
        HALL_CMD_LOGIN_Rsp = 2101,
        HALL_CMD_HeartHeat_Req = 2102,
        HALL_CMD_HeartHeat_Rsp = 2103,
        HALL_CMD_FishGame_Req = 2104,
        HALL_CMD_FishGame_Rsp = 2105,
        HALL_CMD_EnterGame_Req = 2106,
        HALL_CMD_EnterGame_Rsp = 2107,
        HALL_CMD_ExitGame_Req = 2108,
        HALL_CMD_ExitGame_Rsp = 2109,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
