# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.208.0"

default_platform :android

platform :android do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  private_lane :build_project do |options|
    if options[:mask_icon]
      build_number_icon(
        filename: "ic_launcher.png",
        res_dir: "app/src/slots1/res"
      )

      build_number_icon(
        filename: "ic_launcher_foreground.png",
        res_dir: "app/src/slots1/res"
      )
    end
    
    versionCode = options[:version_code] || ENV["BUILD_NUMBER"] || 33
    versionName = ENV["VERSION_NAME"] || "1.0"

    gradle(
      task: options[:task],
      flavor: options[:flavor],
      build_type: options[:build_type],
      properties: {
        'versionCode' => versionCode,
        'versionName' => versionName
      }
    )
  end

  private_lane :build_and_upload do |options|
    latestVersionCode = latest_version_code(
      json_key: ENV["SUPPLY_JSON_KEY"],
      package_name: options[:package_name]
    )

    build_project(
      task: options[:task],
      flavor: options[:flavor],
      build_type: options[:build_type],
      mask_icon: options[:mask_icon],
      version_code: latestVersionCode + 1
    )
    supply(
      track: 'beta',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      json_key: ENV["SUPPLY_JSON_KEY"],
      package_name: options[:package_name],
    )
    notes = (ENV["BUILD_TAG"] || 'Off jenkins') + " - " + last_git_commit[:message]
    File.write("../tmp_changelog.txt", notes)
  end

  desc "Submit a new Alpha Build (sign in the Stage server)"
  lane :build_st do
    build_project(
      task: 'assemble',
      flavor: 'Slots1',
      build_type: 'St',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots1',
      build_type: 'St',
      mask_icon: false,
      package_name: 'com.bagelcode.slots1'
    )
  end

  desc "Submit a new Beta Build (sign in the Production server)"
  lane :build_prod do
    build_project(
      task: 'assemble',
      flavor: 'Slots1',
      build_type: 'Prod',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots1',
      build_type: 'Prod',
      mask_icon: false,
      package_name: 'com.bagelcode.slots1'
    )
  end

  desc "Submit a new Beta Build (sign in the Production server)"
  lane :build_prod_slots3 do
    build_project(
      task: 'assemble',
      flavor: 'Slots3',
      build_type: 'Prod',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots3',
      build_type: 'Prod',
      mask_icon: false,
      package_name: 'com.bagelcode.slots3'
    )
  end

  desc "Submit a new Beta Build (sign in the Production server)"
  lane :build_prod_slots4 do
    build_project(
      task: 'assemble',
      flavor: 'Slots4',
      build_type: 'Prod',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots4',
      build_type: 'Prod',
      mask_icon: false,
      package_name: 'com.cashworldslots.slots1'
    )
  end

  lane :build_team do
    build_project(
      task: 'assemble',
      flavor: 'Slots1',
      build_type: 'Team',
      mask_icon: true
    )
  end

  lane :build_team_slots4 do
    build_project(
      task: 'assemble',
      flavor: 'Slots4',
      build_type: 'Team',
      mask_icon: true
    )
  end

  lane :build_team_slots3 do
    build_project(
      task: 'assemble',
      flavor: 'Slots3',
      build_type: 'Team',
      mask_icon: true
    )
  end

  lane :build_team_contents do
    build_project(
      task: 'assemble',
      flavor: 'Slots1',
      build_type: 'TeamContents',
      mask_icon: true
    )
  end

  desc "Submit a new Alpha Build (sign in the Stage server)"
  lane :build_qa do
    build_project(
      task: 'assemble',
      flavor: 'Slots1',
      build_type: 'Qa',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots1',
      build_type: 'Qa',
      mask_icon: false,
      package_name: 'com.bagelcode.slots1'
    )
  end

  lane :build_qa_slots4 do
    build_project(
      task: 'assemble',
      flavor: 'Slots4',
      build_type: 'Qa',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots4',
      build_type: 'Qa',
      mask_icon: false,
      package_name: 'com.cashworldslots.slots1'
    )
  end

  lane :build_qa_slots3 do
    build_project(
      task: 'assemble',
      flavor: 'Slots3',
      build_type: 'Qa',
      mask_icon: false
    )
    build_and_upload(
      task: 'bundle',
      flavor: 'Slots3',
      build_type: 'Qa',
      mask_icon: false,
      package_name: 'com.bagelcode.slots3'
    )
  end

  lane :latest_version_code_test do |options|
    latestVersionCode = latest_version_code(
      json_key: "google_jenkins_secret.json"
    )
    UI.message "Latest version is #{latestVersionCode}"
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
